package fdlog

import scalatags.Text.all._
import upickle.default._
import scalatags.Text.tags2

import java.time.{Instant, ZoneOffset}
import java.time.format.DateTimeFormatter
import java.util.UUID
import scala.collection.mutable
import java.net.{DatagramPacket, DatagramSocket, InetAddress}
import java.io.{ByteArrayInputStream, ByteArrayOutputStream}
import java.util.zip.{GZIPInputStream, GZIPOutputStream}

// alias to avoid conflicts with scalatags.head / etc
import requests as req

// ----- Data model -----

final case class NodeId(value: UUID)
final case class QsoId(nodeId: NodeId, seq: Long)

final case class Qso(
                      id:            QsoId,
                      time:          Instant,
                      freqHz:        Long,
                      band:          String,   // "40m"
                      mode:          String,   // "CW", "SSB", "DIGI"
                      myCall:        String,
                      theirCall:     String,
                      rstSent:       String,
                      rstRcvd:       String,
                      exchangeSent:  String,   // e.g. "2A IL"
                      exchangeRcvd:  String,   // e.g. "3A WI"
                      operator:      Option[String],
                      notes:         Option[String]
                    )

final case class NodeMeta(
                           nodeId:  NodeId,
                           nextSeq: Long
                         )

final case class LogState(
                           meta: NodeMeta,
                           qsos: Map[QsoId, Qso]
                         )

// API payload when adding a QSO
final case class QsoInput(
                           freqHz:        Long,
                           band:          String,
                           mode:          String,
                           myCall:        String,
                           theirCall:     String,
                           rstSent:       String,
                           rstRcvd:       String,
                           exchangeSent:  String,
                           exchangeRcvd:  String,
                           operator:      Option[String],
                           notes:         Option[String]
                         )

final case class PeersResponse(
                                self:  String,
                                peers: Seq[String]
                              )

// For /api/dupes JSON
final case class DupeGroupDto(
                               band:      String,
                               mode:      String,
                               theirCall: String,
                               qsoIds:    Seq[QsoId]
                             )

// ----- uPickle codecs -----

given uuidRW: ReadWriter[UUID] =
  readwriter[String].bimap[UUID](_.toString, UUID.fromString)

given instantRW: ReadWriter[Instant] =
  readwriter[Long].bimap[Instant](_.toEpochMilli, Instant.ofEpochMilli)

given nodeIdRW: ReadWriter[NodeId]       = macroRW
given qsoIdRW: ReadWriter[QsoId]         = macroRW
given qsoRW: ReadWriter[Qso]             = macroRW
given nodeMetaRW: ReadWriter[NodeMeta]   = macroRW
given logStateRW: ReadWriter[LogState]   = macroRW
given qsoInputRW: ReadWriter[QsoInput]   = macroRW
given peersResponseRW: ReadWriter[PeersResponse] = macroRW
given dupeGroupDtoRW: ReadWriter[DupeGroupDto]   = macroRW

// ----- ADIF export -----

object Adif:
  private val dateFmt =
    DateTimeFormatter.ofPattern("yyyyMMdd").withZone(ZoneOffset.UTC)
  private val timeFmt =
    DateTimeFormatter.ofPattern("HHmmss").withZone(ZoneOffset.UTC)

  private def field(name: String, value: String): String =
    if value == null || value.isEmpty then ""
    else s"<$name:${value.length}>$value"

  def toAdif(qs: Seq[Qso]): String =
    val header =
      """Generated by FDLog (Scala)
        |<adif_ver:5>3.1.0
        |<programid:5>FDLog
        |<EOH>
        |""".stripMargin

    val body = qs.map { q =>
      val date = dateFmt.format(q.time)
      val time = timeFmt.format(q.time)

      val sb = new StringBuilder
      sb.append(field("CALL", q.theirCall))
      sb.append(field("STATION_CALLSIGN", q.myCall))
      sb.append(field("BAND", q.band))
      sb.append(field("MODE", q.mode))
      sb.append(field("RST_SENT", q.rstSent))
      sb.append(field("RST_RCVD", q.rstRcvd))
      sb.append(field("QSO_DATE", date))
      sb.append(field("TIME_ON", time))
      sb.append(field("APP_FDLOG_EXCH_SENT", q.exchangeSent))
      sb.append(field("APP_FDLOG_EXCH_RCVD", q.exchangeRcvd))
      q.operator.foreach(op => sb.append(field("OPERATOR", op)))
      q.notes.foreach(n => sb.append(field("COMMENT", n)))

      sb.append("<EOR>\n")
      sb.toString
    }.mkString

    header + body

// ----- Storage / journal -----

object Storage:

  /** Persist a stable NodeId so this node's QsoId.nodeId doesn't change on restart. */
  def ensureNodeId(p: os.Path): NodeId =
    if os.exists(p) then
      val text = os.read(p)
      read[NodeId](text)
    else
      val id = NodeId(UUID.randomUUID())
      os.write.over(p, write(id, indent = 2), createFolders = true)
      id

  /** Load QSO state from an append-only JSON-lines journal. */
  def loadFromJournal(journalPath: os.Path, nodeIdPath: os.Path): LogState =
    val nodeId = ensureNodeId(nodeIdPath)

    val qsos: Map[QsoId, Qso] =
      if os.exists(journalPath) then
        val lines = os.read.lines(journalPath)
        var m = Map.empty[QsoId, Qso]
        lines.foreach { line =>
          val trimmed = line.trim
          if trimmed.nonEmpty then
            try
              val q = read[Qso](trimmed)
              m = m + (q.id -> q)
            catch case _: Throwable =>
              () // skip bad line
        }
        m
      else
        Map.empty[QsoId, Qso]

    val nextSeq =
      qsos.keysIterator
        .filter(_.nodeId == nodeId)
        .map(_.seq)
        .foldLeft(0L)((acc, s) => math.max(acc, s + 1L))

    LogState(
      meta = NodeMeta(nodeId = nodeId, nextSeq = nextSeq),
      qsos = qsos
    )

  /** Append one or more QSOs to the journal as NDJSON. */
  def appendJournal(journalPath: os.Path, qs: Seq[Qso]): Unit =
    if qs.nonEmpty then
      val sb = new StringBuilder
      qs.foreach { q =>
        sb.append(write(q))
        sb.append('\n')
      }
      os.write.append(journalPath, sb.result(), createFolders = true)

// ----- Compression helpers -----

object Compression:
  def gzip(data: Array[Byte]): Array[Byte] =
    val baos = new ByteArrayOutputStream()
    val g    = new GZIPOutputStream(baos)
    g.write(data)
    g.finish()
    g.close()
    baos.toByteArray

  def gunzip(data: Array[Byte]): Array[Byte] =
    val bais = new ByteArrayInputStream(data)
    val g    = new GZIPInputStream(bais)
    val buf  = new Array[Byte](4000)//todo big enough??
    val baos = new ByteArrayOutputStream()
    var n: Int = g.read(buf)
    while n != -1 do
      baos.write(buf, 0, n)
      n = g.read(buf)
    g.close()
    baos.toByteArray

// ----- In-memory store (thread-safe) -----

class QsoStore(initial: LogState, journalPath: os.Path):

  @volatile private var state: LogState = initial
  private val lock = new AnyRef

  def getState(): LogState = state

  def all(): Seq[Qso] =
    state.qsos.values.toSeq.sortBy(_.time.toEpochMilli)

  def allIds(): Seq[QsoId] =
    state.qsos.keys.toSeq.sortBy(id => (id.nodeId.value.toString, id.seq))

  def has(id: QsoId): Boolean =
    state.qsos.contains(id)

  def findByIds(ids: Seq[QsoId]): Seq[Qso] =
    val m = state.qsos
    ids.flatMap(m.get)

  def createLocalQso(input: QsoInput): Qso =
    val (id, now) = lock.synchronized {
      val s      = state
      val newId  = QsoId(s.meta.nodeId, s.meta.nextSeq)
      val updatedMeta = s.meta.copy(nextSeq = s.meta.nextSeq + 1)
      state = s.copy(meta = updatedMeta)
      (newId, Instant.now())
    }

    val q = Qso(
      id             = id,
      time           = now,
      freqHz         = input.freqHz,
      band           = input.band,
      mode           = input.mode,
      myCall         = input.myCall,
      theirCall      = input.theirCall,
      rstSent        = input.rstSent,
      rstRcvd        = input.rstRcvd,
      exchangeSent   = input.exchangeSent,
      exchangeRcvd   = input.exchangeRcvd,
      operator       = input.operator,
      notes          = input.notes
    )

    lock.synchronized {
      val s = state
      state = s.copy(qsos = s.qsos + (q.id -> q))
    }

    Storage.appendJournal(journalPath, Seq(q))

    q

  /** Merge remote QSOs and append any *new* ones to journal. */
  def merge(remote: Seq[Qso]): Unit =
    val newlyAdded: List[Qso] = lock.synchronized {
      val s       = state
      var m       = s.qsos
      val added   = mutable.ListBuffer.empty[Qso]

      remote.foreach { q =>
        if !m.contains(q.id) then
          m = m + (q.id -> q)
          added += q
      }

      state = s.copy(qsos = m)
      added.toList
    }

    if newlyAdded.nonEmpty then
      Storage.appendJournal(journalPath, newlyAdded)

// ----- Broadcast-based discovery -----

object Discovery:

  private val defaultPort = 49555

  private def discoveryPort: Int =
    sys.env.get("FDLOG_DISCOVERY_PORT")
      .flatMap(_.toIntOption)
      .getOrElse(defaultPort)

  def start(peers: mutable.Set[String], selfUrl: String): Unit =
    startReceiver(peers, selfUrl)
    startBroadcaster(selfUrl)

  private def startBroadcaster(selfUrl: String): Unit =
    val t = new Thread(() => {
      val port = discoveryPort
      val data = selfUrl.getBytes("UTF-8")
      while true do
        try
          val sock = new DatagramSocket()
          sock.setBroadcast(true)
          val packet = new DatagramPacket(
            data,
            data.length,
            InetAddress.getByName("255.255.255.255"),
            port
          )
          sock.send(packet)
          sock.close()
        catch case _: Throwable => ()
        Thread.sleep(5000L) // broadcast every 5s
    })
    t.setDaemon(true)
    t.start()

  private def startReceiver(peers: mutable.Set[String], selfUrl: String): Unit =
    val t = new Thread(() => {
      val port = discoveryPort
      val sock = new DatagramSocket(port)
      val buf  = new Array[Byte](40000)

      while true do
        try
          val packet = new DatagramPacket(buf, buf.length)
          sock.receive(packet)
          val msg = String(
            packet.getData,
            packet.getOffset,
            packet.getLength,
            "UTF-8"
          ).trim

          if msg.nonEmpty && msg != selfUrl then
            peers += msg
        catch case _: Throwable => ()
    })
    t.setDaemon(true)
    t.start()

// ----- Replicator (ID-list + fetch) -----

object Replicator:

  def start(
             store: QsoStore,
             peers: mutable.Set[String],
             selfUrl: String,
             periodSeconds: Int
           ): Unit =
    val t = new Thread(() => {
      while true do
        try
          val peerList = peers.toList
          for peer <- peerList do
            // 1) pull compressed list of QsoId from peer
            try
              val resp = req.get(s"$peer/api/log/ids", readTimeout = 10000)
              if resp.statusCode == 200 then
                val rawBytes = resp.bytes
                val decoded =
                  try Compression.gunzip(rawBytes)
                  catch case _: Throwable => rawBytes

                val ids = read[Seq[QsoId]](String(decoded, "UTF-8"))

                val missingIds = ids.filterNot(store.has)

                if missingIds.nonEmpty then
                  // 2) ask them for just those QSOs
                  val bodyJson = write(missingIds)
                  val fetchResp =
                    req.post(
                      s"$peer/api/log/fetch",
                      data        = bodyJson,
                      readTimeout = 10000
                    )

                  if fetchResp.statusCode == 200 then
                    val qRaw   = fetchResp.bytes
                    val qBytes =
                      try Compression.gunzip(qRaw)
                      catch case _: Throwable => qRaw

                    val qsos = read[Seq[Qso]](String(qBytes, "UTF-8"))
                    store.merge(qsos)
            catch case _: Throwable => ()

            // 3) peer exchange
            try
              val pResp = req.get(s"$peer/api/peers", readTimeout = 5000)
              if pResp.statusCode == 200 then
                val parsed = read[PeersResponse](pResp.text())
                peers ++= parsed.peers.filter(url => url != selfUrl && url.nonEmpty)
            catch case _: Throwable => ()
        catch case _: Throwable => ()

        Thread.sleep(periodSeconds.toLong * 1000L)
    })

    t.setDaemon(true)
    t.start()

// ----- Main app -----

object FdLogApp extends cask.MainRoutes:

  // For /api/dupes JSON
  private case class DupeKey(
                              band:      String,
                              mode:      String,
                              theirCall: String
                            )

  private def computeDupeInfo(qs: Seq[Qso]): (Seq[Qso], Set[QsoId], Seq[DupeGroupDto]) =
    val grouped = qs.groupBy(q => DupeKey(q.band, q.mode, q.theirCall))

    var dupeIds = Set.empty[QsoId]
    val dupeGroups = mutable.Buffer.empty[DupeGroupDto]
    val uniques = mutable.Buffer.empty[Qso]

    grouped.foreach { case (key, list) =>
      val sorted = list.sortBy(_.time.toEpochMilli)
      sorted.headOption.foreach(uniques += _)
      if sorted.size > 1 then
        val dupes = sorted.drop(1)
        dupeIds ++= dupes.map(_.id)
        dupeGroups += DupeGroupDto(
          band      = key.band,
          mode      = key.mode,
          theirCall = key.theirCall,
          qsoIds    = dupes.map(_.id)
        )
    }

    (uniques.toSeq, dupeIds, dupeGroups.toSeq)

  // ----- Config / wiring -----

  private val listenPort: Int =
    sys.env.get("FDLOG_PORT").flatMap(_.toIntOption).getOrElse(8080)

  override def port: Int = listenPort

  // Self URL for peers/discovery
  private val selfBaseUrl: String =
    sys.env.getOrElse("FDLOG_SELF_URL", s"http://127.0.0.1:$listenPort")

  // Seed peers via env: FDLOG_PEERS="http://10.0.0.10:8080,http://10.0.0.11:8080"
  private val peers: mutable.Set[String] =
    mutable.Set.from(
      sys.env
        .get("FDLOG_PEERS")
        .map(_.split(",").map(_.trim).filter(_.nonEmpty))
        .getOrElse(Array.empty[String])
    )

  private val dataDir: os.Path     = os.pwd
  private val journalPath: os.Path = dataDir / "fdlog-qso-journal.ndjson"
  private val nodeIdPath: os.Path  = dataDir / "fdlog-node.json"

  private val initialState: LogState =
    Storage.loadFromJournal(journalPath, nodeIdPath)

  private val store = new QsoStore(initialState, journalPath)

  // Start discovery + replicator
  Discovery.start(peers, selfBaseUrl)
  Replicator.start(store, peers, selfBaseUrl, periodSeconds = 30)

  // ----- Routes -----

  @cask.get("/")
  def index() =
    val allQsos = store.all()
    val (uniqueQsos, dupeIds, _) = computeDupeInfo(allQsos)

    val rows = allQsos.map { q =>
      val dupeFlag = if dupeIds.contains(q.id) then "YES" else ""
      tr(
        if dupeFlag.nonEmpty then (backgroundColor := "#ffe0e0") else (),
        td(q.time.toString),
        td(q.band),
        td(q.mode),
        td(q.myCall),
        td(q.theirCall),
        td(q.exchangeSent),
        td(q.exchangeRcvd),
        td(dupeFlag)
      )
    }

    val page =
      html(
        head(
          tags2.title("FDLog"),
          meta(charset := "utf-8"),
          tags2.style(
            """
              |body { font-family: sans-serif; margin: 1rem 2rem; }
              |table { border-collapse: collapse; width: 100%; }
              |th, td { border: 1px solid #ccc; padding: 4px 8px; font-size: 90%; }
              |th { background: #eee; }
              |.form-grid { display: grid; grid-template-columns: repeat(auto-fit,minmax(120px,1fr)); gap: 0.5rem; }
              |label { font-size: 85%; display: block; }
              |input, select, textarea { width: 100%; box-sizing: border-box; }
              |.dupe { background: #ffe0e0; }
              |""".stripMargin
          )
        ),
        body(
          h1("FDLog"),
          p(
            "This node ID: ",
            code(store.getState().meta.nodeId.value.toString),
            " – Base URL: ",
            code(selfBaseUrl)
          ),
          h2("QSOs"),
          table(
            thead(
              tr(
                th("Time"),
                th("Band"),
                th("Mode"),
                th("My Call"),
                th("Their Call"),
                th("Exch Sent"),
                th("Exch Rcvd"),
                th("Dupe")
              )
            ),
            tbody(rows)
          ),
          p(
            "Unique QSOs: ",
            b(uniqueQsos.size.toString),
            " / Total: ",
            b(allQsos.size.toString),
            " – ",
            a(href := "/api/export/adif")("Export ADIF (unique)"),
            " – ",
            a(href := "/api/export/adif?includeDupes=true")("Export ADIF (all)")
          ),
          h2("Quick QSO Entry"),
          p(
            "Band/Mode presets: ",
            button(`type` := "button", onclick := "setBandMode('80m','CW')")("80m CW"),
            " ",
            button(`type` := "button", onclick := "setBandMode('40m','CW')")("40m CW"),
            " ",
            button(`type` := "button", onclick := "setBandMode('40m','SSB')")("40m SSB"),
            " ",
            button(`type` := "button", onclick := "setBandMode('20m','DIGI')")("20m DIGI")
          ),
          form(
            id := "qsoForm",
             onsubmit := "submitQsoForm(event);",
            div(`class` := "form-grid")(
              div(
                label("Band"),
                input(`type` := "text", id := "band", name := "band", value := "40m")
              ),
              div(
                label("Mode"),
                input(`type` := "text", id := "mode", name := "mode", value := "CW")
              ),
              div(
                label("Freq Hz"),
                input(`type` := "number", id := "freqHz", name := "freqHz", value := "7100000")
              ),
              div(
                label("My Call"),
                input(`type` := "text", id := "myCall", name := "myCall")
              ),
              div(
                label("Their Call"),
                input(`type` := "text", id := "theirCall", name := "theirCall")
              ),
              div(
                label("RST Sent"),
                input(`type` := "text", id := "rstSent", name := "rstSent", value := "599")
              ),
              div(
                label("RST Rcvd"),
                input(`type` := "text", id := "rstRcvd", name := "rstRcvd", value := "599")
              ),
              div(
                label("Exchange Sent"),
                input(`type` := "text", id := "exchangeSent", name := "exchangeSent")
              ),
              div(
                label("Exchange Rcvd"),
                input(`type` := "text", id := "exchangeRcvd", name := "exchangeRcvd")
              ),
              div(
                label("Operator"),
                input(`type` := "text", id := "operator", name := "operator")
              ),
              div(
                label("Notes"),
                textarea(id := "notes", name := "notes")
              )
            ),
            div(
              marginTop := "0.5rem",
              button(`type` := "submit")("Add QSO")
            )
          ),
          h2("Peers"),
          p(
            "This node shares with peers via UDP broadcast discovery and ID-list replication."
          ),
          ul(
            li("Self: ", code(selfBaseUrl)),
            li("Known peers: ", code(peers.mkString(", ")))
          ),
          script(
            raw(
              """
                |function setBandMode(band, mode) {
                |  document.getElementById("band").value = band;
                |  document.getElementById("mode").value = mode;
                |}
                |
                |async function submitQsoForm(ev) {
                |  // Stop the browser from doing a normal form submit to "/"
                |  ev.preventDefault();
                |
                |  const form = document.getElementById("qsoForm");
                |  const data = {
                |    freqHz: parseInt(form.freqHz.value || "0", 10),
                |    band: form.band.value,
                |    mode: form.mode.value,
                |    myCall: form.myCall.value,
                |    theirCall: form.theirCall.value,
                |    rstSent: form.rstSent.value,
                |    rstRcvd: form.rstRcvd.value,
                |    exchangeSent: form.exchangeSent.value,
                |    exchangeRcvd: form.exchangeRcvd.value,
                |    operator: form.operator.value ? form.operator.value : null,
                |    notes: form.notes.value ? form.notes.value : null
                |  };
                |
                |  try {
                |    const resp = await fetch("/api/qso", {
                |      method: "POST",
                |      headers: { "Content-Type": "application/json" },
                |      body: JSON.stringify(data)
                |    });
                |    if (!resp.ok) {
                |      alert("Error saving QSO: " + resp.status);
                |      return;
                |    }
                |    window.location.reload();
                |  } catch (e) {
                |    console.error(e);
                |    alert("Network error");
                |  }
                |}
                |""".stripMargin
            )
          )        )
      )

    cask.Response(
      data    = page.render,
      headers = Seq("Content-Type" -> "text/html; charset=utf-8")
    )

  @cask.post("/api/qso")
  def createQso(request: cask.Request) =
    val input = read[QsoInput](request.text())
    val q = store.createLocalQso(input)
    cask.Response(
      data    = write(q),
      headers = Seq("Content-Type" -> "application/json")
    )

  // Full log (mostly for debugging / legacy)
  @cask.get("/api/log/full")
  def fullLog() =
    cask.Response(
      data    = write(store.all()),
      headers = Seq("Content-Type" -> "application/json")
    )

  // Merge full log (legacy / debug)
  @cask.post("/api/log/merge")
  def mergeLog(request: cask.Request) =
    val qs = read[Seq[Qso]](request.text())
    store.merge(qs)
    cask.Response(
      data    = """{"status":"ok"}""",
      headers = Seq("Content-Type" -> "application/json")
    )

  // Compressed list of all QsoId for replication
  @cask.get("/api/log/ids")
  def logIds() =
    val ids       = store.allIds()
    val jsonBytes = write(ids).getBytes("UTF-8")
    val gz        = Compression.gzip(jsonBytes)

    cask.Response(
      data = gz,
      headers = Seq(
        "Content-Type"     -> "application/json",
        "Content-Encoding" -> "gzip"
      )
    )

  // Given a list of QsoId, return corresponding QSOs (gzipped JSON)
  @cask.post("/api/log/fetch")
  def fetchLogByIds(request: cask.Request) =
    val ids = read[Seq[QsoId]](request.text())
    val qs  = store.findByIds(ids)
    val jsonBytes = write(qs).getBytes("UTF-8")
    val gz        = Compression.gzip(jsonBytes)

    cask.Response(
      data = gz,
      headers = Seq(
        "Content-Type"     -> "application/json",
        "Content-Encoding" -> "gzip"
      )
    )

  @cask.get("/api/peers")
  def getPeers() =
    val payload = PeersResponse(self = selfBaseUrl, peers = peers.toSeq)
    cask.Response(
      data    = write(payload),
      headers = Seq("Content-Type" -> "application/json")
    )

  @cask.post("/api/peers/add")
  def addPeer(request: cask.Request) =
    val url = request.text().trim
    if url.nonEmpty && url != selfBaseUrl then
      peers += url
    cask.Response(
      data    = """{"status":"ok"}""",
      headers = Seq("Content-Type" -> "application/json")
    )

  @cask.get("/api/dupes")
  def dupes() =
    val (_, _, dupeGroups) = computeDupeInfo(store.all())
    cask.Response(
      data    = write(dupeGroups),
      headers = Seq("Content-Type" -> "application/json")
    )

  @cask.get("/api/export/adif")
  def exportAdif(includeDupes: Boolean = false) =
    val allQsos = store.all()
    val (uniqueQsos, _, _) = computeDupeInfo(allQsos)
    val qs = if includeDupes then allQsos else uniqueQsos
    val adif = Adif.toAdif(qs)
    cask.Response(
      data    = adif,
      headers = Seq("Content-Type" -> "text/plain; charset=utf-8")
    )

  initialize()