/*
 * Copyright (c) 2026. Dick Lieber, WA9NNN
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package fdswarm.exporter

import munit.FunSuite
import fdswarm.model.*

import java.time.Instant
import os.*
import io.circe.syntax.*
import fdswarm.StationConfigManager
import fdswarm.MockStartupInfo
import fdswarm.exporter.AdifExporter
import fdswarm.fx.station.StationConfig
import fdswarm.support.TempDirFileHelperSuite

class AdifExporterTest extends TempDirFileHelperSuite :
  val qsoMetadata = fdswarm.model.QsoMetadata.testQsoMetadata

  val testDir = os.temp.dir()
  val station = StationConfig(Callsign("WA9NNN"), "FT-891", "End Fed")
  val stationJson = station.asJson.noSpaces
  os.write.over(testDir / "station.json", stationJson)
  val dummyDirProvider: fdswarm.DirectoryProvider = () => testDir
  val stationManager = new StationConfigManager(fileHelper, MockStartupInfo)
  val exporter = new AdifExporter(stationManager)

  test("AdifExporter should generate correct ADIF"):
    val bandMode = BandMode("40M", "CW")
    val stamp = Instant.parse("2026-02-25T10:00:00Z")
    val qso = Qso(
      callsign = Callsign("K1ABC"),
      exchange = Exchange(FdClass("1A"), "CT"),
      bandMode = bandMode,
      qsoMetadata = fdswarm.model.QsoMetadata.testQsoMetadata,
      stamp = stamp,
      uuid = "unique-id-123"
    )

    val adif = exporter.exportQsos(Seq(qso))
    
    // Check header
    assert(adif.contains("Generated by FdSwarm"))
    assert(adif.contains("<ADIF_VER:5>3.1.4"))
    assert(adif.contains("<EOH>"))
    
    // Check record
    assert(adif.contains("<CALL:5>K1ABC"))
    assert(adif.contains("<BAND:3>40M"))
    assert(adif.contains("<MODE:2>CW"))
    assert(adif.contains("<QSO_DATE:8>20260225"))
    assert(adif.contains("<TIME_ON:6>100000"))
    assert(adif.contains("<STATION_CALLSIGN:6>WA9NNN"))
    assert(adif.contains("<CLASS:2>1A"))
    assert(adif.contains("<ARRL_SECT:2>CT"))
    assert(adif.contains("<EOR>"))

  test("AdifExporter should map internal modes to ADIF modes"):
    val stamp = Instant.parse("2026-02-25T10:00:00Z")

    val qsoPh = Qso(Callsign("K1ABC"), Exchange(FdClass("1A"), "CT"), BandMode("40M", "PH"), qsoMetadata, stamp, "id-ph")
    val qsoDigi = Qso(Callsign("K1ABC"), Exchange(FdClass("1A"), "CT"), BandMode("40M", "DIGI"), qsoMetadata, stamp, "id-digi")
    val qsoCw = Qso(Callsign("K1ABC"), Exchange(FdClass("1A"), "CT"), BandMode("40M", "CW"), qsoMetadata, stamp, "id-cw")

    val adif = exporter.exportQsos(Seq(qsoPh, qsoDigi, qsoCw))
    
    assert(adif.contains("<MODE:3>SSB"), "PH should map to SSB")
    assert(adif.contains("<MODE:4>DATA"), "DIGI should map to DATA")
    assert(adif.contains("<MODE:2>CW"), "CW should remain CW")
