version = "3.8.4"

runner.dialect = scala3

verticalMultiline.atDefnSite = true
verticalMultiline.arityThreshold = 1
verticalMultiline.newlineAfterOpenParen = true

rewrite.rules = [
  RedundantBraces
]


rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = true
