version = "3.8.4"
runner.dialect = scala3
maxColumn = 100

indent.main = 2

continuationIndent {
  callSite = 2
  defnSite = 2
}

docstrings {
  blankFirstLine = unfold
  wrap = fold
}

optIn {
  configStyleArguments = true
  breakChainOnFirstMethodDot = true
}

rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortModifiers
]

newlines.source = fold
