/*
 * Copyright (c) 2026. Dick Lieber, WA9NNN
 *
 * This program is free software: you can redistribute it and/or modify 
 * it under the terms of the GNU General Public License as published by 
 * the Free Software Foundation, either version 3 of the License, or    
 * (at your option) any later version.                                  
 *                                                                      
 * This program is distributed in the hope that it will be useful,      
 * but WITHOUT ANY WARRANTY; without even the implied warranty of       
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        
 * GNU General Public License for more details.                         
 *                                                                      
 * You should have received a copy of the GNU General Public License    
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package fdswarm.replication

import fdswarm.fx.contest.ContestConfig
import fdswarm.model.BandModeOperator
import fdswarm.util.Ids.Id
import fdswarm.util.{CirceGzip, Ids}
import io.circe.Codec
import io.circe.Encoder.AsObject.importedAsObjectEncoder
import io.circe.generic.auto.{deriveDecoder, deriveEncoder}

/**
 * Represents a status message containing information about the current state
 * of a contest communication system.
 *
 * @param hashCount A SHA-512 hash of all the Qsos that have been loggedand how many QSOs.
 * @param bandNodeOperator An instance of BandModeOperator containing information
 *                         about the operator, frequency band, and timestamp.
 * @param id               A unique identifier for the status message, generated by the system.
 * @param contestConfig    Configuration details of the contest, such as callsign,
 *                         class, section, and other metadata.
 */
case class StatusMessage(hashCount: HashCount,
                         bandNodeOperator: BandModeOperator,
                         id: Id = Ids.generateId(),
                         contestConfig: ContestConfig) derives Codec.AsObject:
  def toPacket: Array[Byte] =
    CirceGzip.encode(this)

object StatusMessage:
  def apply(gzipped: Array[Byte]): StatusMessage =
    CirceGzip.decode[StatusMessage](gzipped).toTry.get

case class HashCount(hash: String = "", qsoCount: Int=0) derives Codec.AsObject