loggers {
  "fdlog.store.QsoStore" = "INFO"
  "fdswarm.fx.qso.QsoEntryPanel" = "INFO"
  "fdswarm.StationManager" = "INFO"
  "fdswarm.fx.ConfigModule" = "INFO"
  "fdswarm.replication.NodeStatusService" = "INFO"
  "fdswarm.store.QsoStore" = "INFO"
  "fdswarm.replication.NodeStatusSender" = "INFO"
  "fdswarm.fx.tools.FdHourDialogService" = "INFO"
  "fdswarm.api.QsoRoutes" = "INFO"
  "fdswarm.replication.NodeStatusHandler" = "INFO"
}
