// For instructions on changing log levels, see docs/logging.md
loggers {
  "fdswarm.replication.CallEndpoint" = info
  "fdswarm.fx.qso.QsoEntryPanel" = "INFO"
  "fdswarm.StationManager" = "INFO"
  "fdswarm.fx.ConfigModule" = "INFO"
  "fdswarm.replication.NodeStatusService" = "INFO"
  "fdswarm.replication.NodeStatusSender" = "INFO"
  "fdswarm.fx.tools.FdHourDialogService" = "INFO"
  "fdswarm.api.QsoRoutes" = "INFO"
  "fdswarm.replication.NodeStatusHandler" = "INFO"
  "fdswarm.store.QsoStore" = "INFO"
  "fdswarm.replication.StatusProcessor" = "INFO"
  "fdswarm.store.ReplicationSupport" = "INFO"
  "fdswarm.replication.MulticastTransport" = "TRACE"
}
