/*
 * Copyright (c) 2026. Dick Lieber, WA9NNN
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package fdswarm.exporter

import fdswarm.model.Qso
import java.time.format.DateTimeFormatter
import java.time.ZoneOffset
import fdswarm.StationConfigManager
import jakarta.inject.{Inject, Singleton}

@Singleton
class AdifExporter @Inject()(stationManager: StationConfigManager):

  def exportQsos(qsos: Seq[Qso]): String =
    val header = "Generated by FdSwarm\n<ADIF_VER:5>3.1.4\n<EOH>\n"
    val records = qsos.map(toAdifRecord).mkString("\n")
    header + records

  private val dateFormatter = DateTimeFormatter.ofPattern("yyyyMMdd").withZone(ZoneOffset.UTC)
  private val timeFormatter = DateTimeFormatter.ofPattern("HHmmss").withZone(ZoneOffset.UTC)

  private def toAdifRecord(qso: Qso): String =
    val call = qso.callsign.value
    val band = qso.bandMode.band.name.toUpperCase
    val mode = mapMode(qso.bandMode.mode)
    val rstSent = "59" // Default for field day
    val rstRcvd = "59"
    val date = dateFormatter.format(qso.stamp)
    val time = timeFormatter.format(qso.stamp)
    val classSent = qso.exchange.fdClass.toString
    val section = qso.exchange.sectionCode
    val ownCall = stationManager.stationConfig.operator.value

    val fields = StringBuilder()
    appendField(fields, "CALL", call)
    appendField(fields, "BAND", band)
    appendField(fields, "MODE", mode)
    appendField(fields, "RST_SENT", rstSent)
    appendField(fields, "RST_RCVD", rstRcvd)
    appendField(fields, "QSO_DATE", date)
    appendField(fields, "TIME_ON", time)
    appendField(fields, "STATION_CALLSIGN", ownCall)
    appendField(fields, "CLASS", classSent)
    appendField(fields, "ARRL_SECT", section)
    
    fields.append("<EOR>")
    fields.toString()

  private def mapMode(mode: String): String =
    mode.toUpperCase match
      case "PH" => "SSB"
      case "DIGI" => "DATA"
      case other => other

  private def appendField(sb: StringBuilder, name: String, value: String): Unit =
    if value.nonEmpty then
      sb.append(s"<$name:${value.length}>$value ")
