fdswarm {

  # shown in the Modes list
  modes = ["CW", "PH", "DIGI"]

  # shown in the Bands list (match your HamBandCatalog bandName values)
  bands = ["160m", "80m", "40m", "20m", "15m", "10m", "6m", "2m"]

  hamBands = [

    # Order is the order that will appear UIs.
    {
      bandName = "160m"
      startFrequencyHz = 1800000
      endFrequencyHz = 2000000
      bandClass = "MF"
      regions = [ALL]
    },

    # HF
    {
      bandName = "80m"
      startFrequencyHz = 3500000
      endFrequencyHz = 4000000
      bandClass = "HF"
      regions = [ALL]
    },
    {
      bandName = "60m"
      startFrequencyHz = 5250000
      endFrequencyHz = 5450000
      bandClass = "HF"
      ituRegionAvailability = {
        type = "VariesByCountry"
      }
    },
    {
      bandName = "40m"
      startFrequencyHz = 7000000
      endFrequencyHz = 7300000
      bandClass = "HF"
      regions = [ALL]
    },
    {
      bandName = "30m"
      startFrequencyHz = 10100000
      endFrequencyHz = 10150000
      bandClass = "HF"
      regions = [ALL]
    },
    {
      bandName = "20m"
      startFrequencyHz = 14000000
      endFrequencyHz = 14350000
      bandClass = "HF"
      regions = [ALL]
    },
    {
      bandName = "15m"
      startFrequencyHz = 21000000
      endFrequencyHz = 21450000
      bandClass = "HF"
      regions = [ALL]
    },
    {
      bandName = "10m"
      startFrequencyHz = 28000000
      endFrequencyHz = 29700000
      bandClass = "HF"
      regions = [ALL]
    },

    # VHF
    {
      bandName = "6m"
      startFrequencyHz = 50000000
      endFrequencyHz = 54000000
      bandClass = "VHF"
      regions = [ALL]
    },
    {
      bandName = "4m"
      startFrequencyHz = 70000000
      endFrequencyHz = 70500000
      bandClass = "VHF"
      ituRegionAvailability = {
        type = "RegionsOnly"
        regions = ["R1", "R3"]
      }
    },
    {
      bandName = "2m"
      startFrequencyHz = 144000000
      endFrequencyHz = 148000000
      bandClass = "VHF"
      regions = [ALL]
    },

    # UHF
    {
      bandName = "1.25m"
      startFrequencyHz = 219000000
      endFrequencyHz = 225000000
      bandClass = "VHF"
      ituRegionAvailability = {
        type = "RegionsOnly"
        regions = ["R2"]
      }
    },
    {
      bandName = "70cm"
      startFrequencyHz = 420000000
      endFrequencyHz = 450000000
      bandClass = "UHF"
      regions = [ALL]
    },
    {
      bandName = "33cm"
      startFrequencyHz = 902000000
      endFrequencyHz = 928000000
      bandClass = "UHF"
      regions = [R2]
    },
    {
      bandName = "23cm"
      startFrequencyHz = 1240000000
      endFrequencyHz = 1300000000
      bandClass = "UHF"
      regions = [ALL]
    },

    # SHF
    {
      bandName = "13cm"
      startFrequencyHz = 2300000000
      endFrequencyHz = 2450000000
      bandClass = "SHF"
      regions = [ALL]
    },
    {
      bandName = "9cm"
      startFrequencyHz = 3300000000
      endFrequencyHz = 3500000000
      bandClass = "SHF"
      regions = [ALL]
    },
    {
      bandName = "6cm"
      startFrequencyHz = 5650000000
      endFrequencyHz = 5925000000
      bandClass = "SHF"
      regions = [ALL]
    },
    {
      bandName = "3cm"
      startFrequencyHz = 10000000000
      endFrequencyHz = 10500000000
      bandClass = "SHF"
      regions = [ALL]
    }

  ]
}
