name: Build and Package

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'
      - name: Run tests
        timeout-minutes: 10
        run: ./mill --no-daemon fdswarm.test.testLocal

      - name: Ensure mill daemon is stopped
        if: always()
        run: ./mill --no-daemon shutdown
#      - name: Run tests
#        run: ./mill --no-daemon fdswarm.test.testLocal
  package-windows:
    name: Package Windows (MSI)
    needs: test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'

      - name: Build winMsi
        run: ./mill.bat fdswarm.winMsi

      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: FdSwarm-Windows-MSI
          path: out/fdswarm/winMsi.dest/jpackage-win-*/*.msi

  package-macos:
    name: Package macOS (PKG)
    needs: test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'

      - name: Build macPkg
        run: ./mill fdswarm.macPkg

      - name: Upload PKG artifact
        uses: actions/upload-artifact@v4
        with:
          name: FdSwarm-macOS-PKG
          path: out/fdswarm/macPkg.dest/jpackage/*.pkg